export enum SYSTEM_CODE {
	BLOG_TITLE_EXIST_SYSTEM = "BLOG_TITLE_EXIST_SYSTEM",
	POST_NOT_FOUND = "POST_NOT_FOUND",
	DATA_UPDATE_BLOG_INVALID = "DATA_UPDATE_BLOG_INVALID",
	PERMISSION_DENIED = "PERMISSION_DENIED",
	TOKEN_IS_INVALID = "TOKEN_IS_INVALID",
	TOKEN_IS_NOT_ALLOW_TO_REFRESH = "TOKEN_IS_NOT_ALLOW_TO_REFRESH",
	USER_NAME_EXIST_SYSTEM = "USER_NAME_EXIST_SYSTEM",
	USER_NOT_FOUND = "USER_NOT_FOUND",
	SUCCESS = "SUCCESS",
	USER_NAME_OR_PASSWORD_IS_NOT_CORRECT = "USER_NAME_OR_PASSWORD_IS_NOT_CORRECT",
	EMAIL_EXIST_SYSTEM = "EMAIL_EXIST_SYSTEM",
}
